{
 "title": "Environmental Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Carbon Dioxide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Carbon Dioxide Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "sensor_co2_ppm", "legendFormat": "co2" }
   ]
  },
  {
   "title": "Average Carbon Dioxide in the Last Hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sensor_co2_ppm[1h])",
     "legendFormat": "max co2 last hour"
    }
   ]
  },
  { "title": "Temperature and Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Temperature and Relative Humidity Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "sensor_temperature_f", "legendFormat": "temperature" },
    {
     "expr": "sensor_relative_humidity_percent",
     "legendFormat": "relative humidity"
    }
   ]
  },
  {
   "title": "Current Temperature and Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensor_temperature_f", "legendFormat": "temperature" },
    {
     "expr": "sensor_relative_humidity_percent",
     "legendFormat": "relative humidity"
    }
   ]
  },
  { "title": "Particulate Matter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Particulate Matter Over Time (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "sensor_pm10_ug_per_m3", "legendFormat": "PM1.0" },
    { "expr": "sensor_pm25_ug_per_m3", "legendFormat": "PM2.5" },
    { "expr": "sensor_pm100_ug_per_m3", "legendFormat": "PM10.0" }
   ]
  },
  {
   "title": "Average Particulate Matter Over 12hrs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sensor_pm10_ug_per_m3[12h])",
     "legendFormat": "PM1.0"
    },
    {
     "expr": "avg_over_time(sensor_pm25_ug_per_m3[12h])",
     "legendFormat": "PM2.5"
    },
    {
     "expr": "avg_over_time(sensor_pm100_ug_per_m3[12h])",
     "legendFormat": "PM10.0"
    }
   ]
  },
  {
   "title": "Particulate Matter Counts Per 0.1L of Air",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sensor_p_03_num_per_decileter", "legendFormat": "p_03" },
    { "expr": "sensor_p_05_num_per_decileter", "legendFormat": "p_05" },
    { "expr": "sensor_p_10_num_per_decileter", "legendFormat": "p_10" },
    { "expr": "sensor_p_25_num_per_decileter", "legendFormat": "p_25" },
    { "expr": "sensor_p_50_num_per_decileter", "legendFormat": "p_50" },
    { "expr": "sensor_p_100_num_per_decileter", "legendFormat": "p_100" }
   ]
  }
 ]
}